name: Deploy To S3

on:
  pull_request:
    types:
      - closed
  workflow_dispatch:

jobs:
  deploy:
    if: github.event.pull_request.merged == true || github.event_name == 'workflow_dispatch'
    runs-on: ubuntu-latest
    env:
      DATOCMS_API_KEY: ${{ secrets.DATOCMS_API_KEY }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Build
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: "npm"
      - name: Install modules
        run: npm ci
      - name: Build application
        run: npm run build
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.S3_BUCKET_REGION }}
      - name: Deploy to S3
        run: aws s3 sync --delete ./dist/ s3://${{ secrets.S3_BUCKET }}
      - name: Create CloudFront invalidation
        run: aws cloudfront create-invalidation --distribution-id ${{ secrets.CLOUDFRONT_DISTRIBUTION_ID }} --paths "/*"
